[build]
  command = "pnpm install && pnpm run build"  # Gerekli paketleri yükle ve projeyi derle
  publish = "dist"  # Derlenen dosyaların bulunduğu dizin

[build.environment]
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"  # Chromium indirmesini atla

[build.processing]
  node_modules = "true"  # node_modules dizinini sakla, gerektiğinde kullan

[build.lifecycle]
  onBuild = "pnpm run puppeteer-script"  # Netlify'in derleme tamamlandığında Puppeteer komutunu çalıştırmasını sağla
