export const GET_ANIME_CARDS = "GET_ANIME_CARDS"
export const SET_ANIME_DATA = "SET_ANIME_DATA"

export const REQUEST_SET_FAVORI_ANIMES = "REQUEST_SET_FAVORI_ANIMES"

export const ADD_ANIME_REQUEST = "ADD_ANIME_REQUEST";
export const ADD_ANIME_SUCCESS = "ADD_ANIME_SUCCESS";

export const GET_ANIME_INFOS_REQUEST = "GET_ANIME_INFOS_REQUEST";
export const SET_ANIME_INFOS_REQUEST = "SET_ANIME_INFOS_REQUEST";
export const SET_ANIME_INFOS = "SET_ANIME_INFOS";

export const SET_ANIME_EPISODESBYID = "SET_ANIME_EPISODESBYID";
export const GET_ANIME_EPISODES_BYID_REQUEST = "GET_ANIME_EPISODES_BYID_REQUEST";

export const ADD_NEW_EPISODE_REQUEST = "ADD_NEW_EPISODE_REQUEST";

export const GET_ANIME_EPISODESBYCOUNT = "SET_ANIME_EPISODESBYCOUNT";
export const SET_ANIME_EPISODESBYCOUNT = "SET_ANIME_EPISODESBYCOUNT";