export const GET_HOMEPAGE_ANIMES = "GET_HOMEPAGE_ANIMES";
export const SET_HOMEPAGE_ANIMES = "SET_HOMEPAGE_ANIMES";

export const SET_ANIMES = "SET_ANIMES";
export const GET_ANIMES = "GET_ANIMES";

export const ADD_NEW_ANIME_REQUEST = "ADD_NEW_ANIME_REQUEST";
export const ADD_NEW_ANIME_SUCCESS = "ADD_NEW_ANIME_SUCCESS";
export const ADD_NEW_ANIME_FAILURE = "ADD_NEW_ANIME_FAILURE";

export const SET_REQUEST_STATUS = "SET_REQUEST_STATUS";
export const GET_REQUEST_STATUS = "GET_REQUEST_STATUS";

export const ADD_NEW_EPISODE_REQUEST = "ADD_NEW_EPISODE_REQUEST";
export const ADD_NEW_EPISODE_SUCCESS = "ADD_NEW_EPISODE_SUCCESS";
export const ADD_NEW_EPISODE_FAILURE = "ADD_NEW_EPISODE_FAILURE";

export const UPDATE_EPISODE_REQUEST = "UPDATE_EPISODE_REQUEST";
export const UPDATE_ANIME_REQUEST = "UPDATE_ANIME_REQUEST";

export const GET_ANIME_REQUEST = "GET_ANIME_REQUEST";

export const SET_ANIME_INFO = "SET_ANIME_INFO";